### ISSUE TITLE
Gerber files?

### ISSUE THREAD

**Issue by lazylester** [fixedd/RPi_Relay_Interface#1]
it would be great if you could publish the Gerber files for this little pcb. This is what the fab houses need in order to make boards. Any chance you have the files available? As far as I know, Eagle software can produce this format (274X format, according to one fab house I contacted).
Thanks in advance

**Comment by fixedd** [comment]
If you're having a fab put these together you could probably get it to be about 1/2 the size... I intentionally went bigger as it'd be easier to hand solder/assemble.

That said, I'll see if I can easily output the files in Gerber format.

**Comment by fixedd** [comment]
Yeah, it looks like it's going to require more research than I'm willing to put in right now. If you want to put it together and issue a pull request, I'll happily merge though.

Thanks.
